# Generated by Django 4.0.2 on 2022-03-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='dp/default.png', null=True, upload_to='dp/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('Not Specified', 'Not Specified'), ('Accounting and Finance', 'Accounting and Finance'), ('Economics', 'Economics'), ('Management', 'Management'), ('Marketing and International Business', 'Marketing and International Business'), ('Architecture', 'Architecture'), ('Civil and Environmental Engineering', 'Civil and Environmental Engineering'), ('Electrical and Computer Engineering', 'Electrical and Computer Engineering'), ('Mathematics and Physics', 'Mathematics and Physics'), ('English and Modern Languages', 'English and Modern Languages'), ('Political Science and Sociology', 'Political Science and Sociology'), ('Law', 'Law'), ('History and Philosophy', 'History and Philosophy'), ('Biochemistry and Microbiology', 'Biochemistry and Microbiology'), ('Environmental Science and Management', 'Environmental Science and Management'), ('Pharmaceutical Sciences', 'Pharmaceutical Sciences'), ('Public Health', 'Public Health')], default='Not Specified', max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('Not Specified', 'Not Specified'), ('Accounting and Finance', 'Accounting and Finance'), ('Economics', 'Economics'), ('Management', 'Management'), ('Marketing and International Business', 'Marketing and International Business'), ('Architecture', 'Architecture'), ('Civil and Environmental Engineering', 'Civil and Environmental Engineering'), ('Electrical and Computer Engineering', 'Electrical and Computer Engineering'), ('Mathematics and Physics', 'Mathematics and Physics'), ('English and Modern Languages', 'English and Modern Languages'), ('Political Science and Sociology', 'Political Science and Sociology'), ('Law', 'Law'), ('History and Philosophy', 'History and Philosophy'), ('Biochemistry and Microbiology', 'Biochemistry and Microbiology'), ('Environmental Science and Management', 'Environmental Science and Management'), ('Pharmaceutical Sciences', 'Pharmaceutical Sciences'), ('Public Health', 'Public Health')], default='Not Specified', max_length=100, null=True)),
                ('is_chairman', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(blank=True, choices=[('Not Specified', 'Not Specified'), ("Registrar's Office", "Registrar's Office"), ("Proctor's Office", "Proctor's Office"), ('Office of External Affairs', 'Office of External Affairs'), ('Office of Graduate Studies', 'Office of Graduate Studies'), ('Office of Student Affairs', 'Office of Student Affairs'), ('Financial Aid Office', 'Financial Aid Office'), ('NSU Startups Next (NSUSN)', 'NSU Startups Next (NSUSN)')], default='Not Specified', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
